language: java
addons:
  apt:
     packages:
         - sshpass
jdk:
- oraclejdk8
install: true
script:
- ./gradlew test
before_deploy:
## Run the travis setup, will download install4j and configure it
- chmod +x ./.travis/setup && ./.travis/setup
## Add the travis build number to the game engine version
- GAME_CONFIG=game_engine.properties
- ENGINE_VERSION=$(grep "engine_version" $GAME_CONFIG | sed 's/.*= *//g')
- export TAGGED_VERSION="$ENGINE_VERSION.$TRAVIS_BUILD_NUMBER"
# Update install4j to have the build number in the install folder
- sed -i "s/shortName=\"TripleA\"/shortName=\"TripleA-$TAGGED_VERSION\"/" build.install4j
- sed -i "s/engine_version.*/engine_version = $TAGGED_VERSION/" $GAME_CONFIG
## Download tutorial map
- mkdir -p maps
- (cd maps; wget https://github.com/triplea-maps/tutorial/releases/download/0.123/tutorial.zip)
## Create the installers
- ./gradlew release
- ls build/releases/

## Push a tag to github, will trigger the releases process 
- chmod +x ./.travis/push_tag && ./.travis/push_tag
## rest is commented out, work in progress.. does not work and needs some debugging.
#- echo "showing build artifacts" && ls build/distributions/
#- DEPLOY_DEST="$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
#- LOBBY_ARTIFACT="triplea-${TAGGED_VERSION}-server.zip"
#- export SSHPASS=$DEPLOY_PASS
#- sshpass -e scp build/distributions/$LOBBY_ARTIFACT $DEPLOY_DEST
#- sshpass -e scp .travis/prerelease_lobby_install.sh $DEPLOY_DEST
#- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/prerelease_lobby_install.sh $LOBBY_ARTIFACT
#- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST 'bash -s' < ./.travis/update_maps
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  ## This is the list of files to be deployed to github releases
  file:
    - build/libs/triplea-${TAGGED_VERSION}-all.jar
    - build/releases/triplea_windows-x64_${TAGGED_VERSION}.exe
    - build/releases/triplea_windows_${TAGGED_VERSION}.exe
    - build/releases/triplea_macos_${TAGGED_VERSION}.dmg
    - build/releases/triplea_unix_${TAGGED_VERSION}.sh
    - build/distributions/triplea-${TAGGED_VERSION}-all_platforms.zip
    - build/distributions/triplea-${TAGGED_VERSION}-bots.zip
    - build/distributions/triplea-${TAGGED_VERSION}-server.zip
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    branches:
      only:
        - master
